language: objective-c
osx_image: xcode11.6

before_install:
  - gem install cocoapods -v '1.6.1'
  - brew install carthage

install: 
  - pushd browser-sign-in
  - pod install --repo-update
  - popd
  - pushd custom-sign-in
  - pod install --repo-update
  - popd
  - pushd browser-sign-in-and-biometric-storage
  - pod install --repo-update
  - popd
  - pushd build-tests/ObjcTest
  - pod install --repo-update
  - popd
  - pushd build-tests/CarthageTest
  - carthage update
  - popd

script:
  - set -o pipefail && xcodebuild -workspace browser-sign-in/OktaBrowserSignIn.xcworkspace -scheme OktaBrowserSignIn -destination platform\=iOS\ Simulator,OS\=latest,name\=iPhone\ 11 build | xcpretty
  - set -o pipefail && xcodebuild -workspace browser-sign-in/OktaBrowserSignIn.xcworkspace -scheme OktaBrowserSignIn -destination platform\=iOS\ Simulator,OS\=11.4,name\=iPhone\ 6 build | xcpretty
  - set -o pipefail && xcodebuild -workspace custom-sign-in/OktaNativeLogin.xcworkspace -scheme OktaNativeLogin -destination platform\=iOS\ Simulator,OS\=latest,name\=iPhone\ 11 build | xcpretty
  - set -o pipefail && xcodebuild -workspace custom-sign-in/OktaNativeLogin.xcworkspace -scheme OktaNativeLogin -destination platform\=iOS\ Simulator,OS\=11.4,name\=iPhone\ 6 build | xcpretty
  - set -o pipefail && xcodebuild -workspace browser-sign-in-and-biometric-storage/OktaSignInAndStorage.xcworkspace -scheme OktaBrowserSignIn -destination platform\=iOS\ Simulator,OS\=latest,name\=iPhone\ 11 build | xcpretty
  - set -o pipefail && xcodebuild -project build-tests/CarthageTest/CarthageTest.xcodeproj -scheme CarthageTest -destination platform\=iOS\ Simulator,OS\=latest,name\=iPhone\ 11 build | xcpretty
  - set -o pipefail && xcodebuild -workspace build-tests/ObjcTest/ObjcTest.xcworkspace -scheme ObjcTest -destination platform\=iOS\ Simulator,OS\=latest,name\=iPhone\ 11 build | xcpretty

notifications:
  slack:
    on_pull_requests: false
    on_success: never
    on_failure: always
    rooms:
     - secure: llwX53NUK+utV8UEFtzXTt5OuhXg+rx/Y3beFNBp7nwASI1k1cpYk8gHhDM6Kj14ydDGtwYd6bL4QcKWWzrA8Hc7EPpXyfgfxF7lDVxIbm62E3rSwqf2XpoNAo0EzcPvjwAGsQnydQUiQR7tR0JTzaHTX+685XreQeQyZXiIB9eWxXCaAkVCRfuoxngcAOXNw1IRMzaRt0pyYbu4qZ0RAA4bLwjlc5RqhAUllGszxX7KCSIJwAa4kXIYT/EsBC1mKeyCdvihvFYp6rPjTDL/J8w8+r9v9SVq8n6/LMcRdEpl8gOIQ3+oLzB1UcX5zWItrVqSXZ221d6z432Vu+mR5olhbcxULkfVZwtTW6tiR/5JkGxI08k5aZAmZupOjMlJN2UJtBxkAUhthCLKPXsrwU0RnW7pOeiH5CKECCsT9S06ZW2VvEJ+CZ1WOqzYtp18Kcq/VqbFqX/ubEy80m0YgnDugLGcwEUrDZFn44g+hu2B59TJMudeOTWEEk6bdy+XTNY4Ufd0uqCoHwBZQICKIXqhxMuxcRYdbFeguTzwu1R7OYagwL9S0PC/RoqrhoiN3vs/KTEVZp7yZLZautT/0cbuDQzfZzJ6RXJZzzNmrQ7Wof9lrNObJgDDdL+dZW9Umv7ELpTjqJicOlih6USjtMq+e+tBiUl/mHMFVnxbZX8=
